package com.zhaoxi.Open_source_Android.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhaoxi.Open_source_Android.common.bean.DigitalSignBean;
import com.zhaoxi.Open_source_Android.common.bean.SimpleAssetBean;
import com.zhaoxi.Open_source_Android.net.bean.AssetsBean;

import com.zhaoxi.Open_source_Android.db.greendao.DigitalSignBeanDao;
import com.zhaoxi.Open_source_Android.db.greendao.SimpleAssetBeanDao;
import com.zhaoxi.Open_source_Android.db.greendao.AssetsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig digitalSignBeanDaoConfig;
    private final DaoConfig simpleAssetBeanDaoConfig;
    private final DaoConfig assetsBeanDaoConfig;

    private final DigitalSignBeanDao digitalSignBeanDao;
    private final SimpleAssetBeanDao simpleAssetBeanDao;
    private final AssetsBeanDao assetsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        digitalSignBeanDaoConfig = daoConfigMap.get(DigitalSignBeanDao.class).clone();
        digitalSignBeanDaoConfig.initIdentityScope(type);

        simpleAssetBeanDaoConfig = daoConfigMap.get(SimpleAssetBeanDao.class).clone();
        simpleAssetBeanDaoConfig.initIdentityScope(type);

        assetsBeanDaoConfig = daoConfigMap.get(AssetsBeanDao.class).clone();
        assetsBeanDaoConfig.initIdentityScope(type);

        digitalSignBeanDao = new DigitalSignBeanDao(digitalSignBeanDaoConfig, this);
        simpleAssetBeanDao = new SimpleAssetBeanDao(simpleAssetBeanDaoConfig, this);
        assetsBeanDao = new AssetsBeanDao(assetsBeanDaoConfig, this);

        registerDao(DigitalSignBean.class, digitalSignBeanDao);
        registerDao(SimpleAssetBean.class, simpleAssetBeanDao);
        registerDao(AssetsBean.class, assetsBeanDao);
    }
    
    public void clear() {
        digitalSignBeanDaoConfig.clearIdentityScope();
        simpleAssetBeanDaoConfig.clearIdentityScope();
        assetsBeanDaoConfig.clearIdentityScope();
    }

    public DigitalSignBeanDao getDigitalSignBeanDao() {
        return digitalSignBeanDao;
    }

    public SimpleAssetBeanDao getSimpleAssetBeanDao() {
        return simpleAssetBeanDao;
    }

    public AssetsBeanDao getAssetsBeanDao() {
        return assetsBeanDao;
    }

}
