package com.zhaoxi.Open_source_Android.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zhaoxi.Open_source_Android.common.bean.DigitalSignBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DIGITAL_SIGN_BEAN".
*/
public class DigitalSignBeanDao extends AbstractDao<DigitalSignBean, Long> {

    public static final String TABLENAME = "DIGITAL_SIGN_BEAN";

    /**
     * Properties of entity DigitalSignBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StrContent = new Property(1, String.class, "strContent", false, "STR_CONTENT");
        public final static Property SignContent = new Property(2, String.class, "signContent", false, "SIGN_CONTENT");
        public final static Property SignDateTime = new Property(3, String.class, "signDateTime", false, "SIGN_DATE_TIME");
    }


    public DigitalSignBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DigitalSignBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DIGITAL_SIGN_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"STR_CONTENT\" TEXT," + // 1: strContent
                "\"SIGN_CONTENT\" TEXT," + // 2: signContent
                "\"SIGN_DATE_TIME\" TEXT);"); // 3: signDateTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DIGITAL_SIGN_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DigitalSignBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String strContent = entity.getStrContent();
        if (strContent != null) {
            stmt.bindString(2, strContent);
        }
 
        String signContent = entity.getSignContent();
        if (signContent != null) {
            stmt.bindString(3, signContent);
        }
 
        String signDateTime = entity.getSignDateTime();
        if (signDateTime != null) {
            stmt.bindString(4, signDateTime);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DigitalSignBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String strContent = entity.getStrContent();
        if (strContent != null) {
            stmt.bindString(2, strContent);
        }
 
        String signContent = entity.getSignContent();
        if (signContent != null) {
            stmt.bindString(3, signContent);
        }
 
        String signDateTime = entity.getSignDateTime();
        if (signDateTime != null) {
            stmt.bindString(4, signDateTime);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DigitalSignBean readEntity(Cursor cursor, int offset) {
        DigitalSignBean entity = new DigitalSignBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // strContent
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // signContent
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // signDateTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DigitalSignBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStrContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSignContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSignDateTime(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DigitalSignBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DigitalSignBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DigitalSignBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
